project_id = "tjfiqnaskbalqcktmpbu"

[functions.speech-to-text]
verify_jwt = false

[functions.recommend-projects]
verify_jwt = false

[functions.extract-entity-ids]
verify_jwt = false

[functions.n8n-document-proxy]
verify_jwt = false

[functions.forgot-password-reset]
verify_jwt = false

[functions.forgot-password-send-otp]
verify_jwt = false

[functions.forgot-password-verify-otp]
verify_jwt = false

[functions.parse-document]
verify_jwt = false

[functions.send-otp-email]
verify_jwt = false
