[build]
  command = "rm -rf node_modules package-lock.json .npm && npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  NODE_VERSION = "22.20.0"
  NPM_VERSION = "10.9.3"
  NPM_FLAGS = "--legacy-peer-deps"