// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjfiqnaskbalqcktmpbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqZmlxbmFza2JhbHFja3RtcGJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MDg2NjksImV4cCI6MjA2NTE4NDY2OX0.7r6NY_H6v7EjU-E0Mr4TCHwxdOzQiAJ8ZyuZ_BA_UU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);